#!/usr/bin/env ruby

def js2coffee(file)
  new_name = file.gsub(/js$/, "coffee")

  save(`js2coffee #{file}`, new_name)
end

def find(pattern)
  Dir.glob("*#{pattern}*")
end

def save(data, file_name)
  File.open(file_name, 'w') {|f| f.write(data) }
end

#js_files = Dir.glob("*.js")
#js_files.each do |file|

$stdin.each_line do |file|
  js2coffee file
end

#puts find(ARGV.first)

#$stdin.each_line do |line|
  #new_name = line

  #command = <<-BASH
    #js2coffee #{line} > #{new_name}
  #BASH

  #system(command)
#end
